name: GitHub metrics
on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches: "master"
  workflow_dispatch:
jobs:
  # The job below generates the images displayed on lowlighter/lowlighter
  # You can reuse these steps if you want to have a profile page similar to mine.
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:
      - name: Personal metrics
        uses: lowlighter/metrics@master
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "header, repositories"
          plugin_lines: yes
          plugin_isocalendar: yes
          config_timezone: Asia/Shanghai
          config_order: base.header, isocalendar, base.repositories
          config_padding: 10%

      - name: Personal metrics (additional)
        uses: lowlighter/metrics@master
        with:
          filename: metrics.additional.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_facts: no
          plugin_habits_charts: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot
          plugin_languages_skipped: viewv
          plugin_stargazers: yes
          plugin_stars: yes
          plugin_stars_limit: 3
          config_timezone: Asia/Shanghai
          config_order: languages, pagespeed, habits, stargazers, stars

  github-metrics:
    needs: [github-metrics-personal]
    runs-on: ubuntu-latest
    if: "github.repository == 'viewv/viewv'"
    steps:
      # Classic template with header and repositories sections
      - name: Classic template
        uses: lowlighter/metrics@master
        with:
          filename: metrics.classic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "header, repositories"
          plugin_lines: yes
          plugins_errors_fatal: yes
          config_timezone: Asia/Shanghai

      # Terminal template with header and metadata sections
      - name: Terminal template
        uses: lowlighter/metrics@master
        with:
          template: terminal
          filename: metrics.terminal.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "header, metadata"
          plugins_errors_fatal: yes
          config_timezone: Asia/Shanghai

      # Display recently played music
      # Note that :
      # - "plugin_music_mode", "plugin_music_provider" and "plugin_music_token" are all required
      - name: Spotify music
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.music.svg
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_mode: playlist
          plugin_music_playlist: https://open.spotify.com/embed/playlist/37i9dQZF1EM25z2Kaa9YFW # Extracted source link
          plugin_music_limit: 4

      # Display coding habits and recent activity
      # Don't forget to setup timezone for accurate metrics
      - name: Habits plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.habits.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugins_errors_fatal: yes
          config_timezone: Asia/Shanghai

      # Display most used languages
      # You can ignore some languages and skip some repositories if you want
      - name: Languages plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot
          plugin_languages_skipped: viewv
          plugins_errors_fatal: yes
          config_timezone: Asia/Shanghai

      # Display ratio of open/closed/merged issues and pull requests
      - name: Follow-up plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.followup.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_followup: yes
          plugins_errors_fatal: yes
          config_timezone: Asia/Shanghai

      # Display number of line changed
      # Note that :
      # - This is part of "repositories" section, so you need to enable it
      - name: Lines plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.lines.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "repositories"
          plugin_lines: yes
          plugins_errors_fatal: yes
          config_timezone: Asia/Shanghai

      # Display isometric calendar (365 days)
      - name: Isocalendar plugin (full year)
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugins_errors_fatal: yes
          config_timezone: Asia/Shanghai

      # Display starred topics (as icons)
      # Note that :
      # - Only topics with an icon will be displayed (most of majors topics have one anyway)
      - name: Topics plugin (mastered)
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.topics.mastered.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_topics: yes
          plugin_topics_mode: mastered
          plugins_errors_fatal: yes
          config_timezone: Asia/Shanghai

      # Display your latest starred repositories
      - name: Stars plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.stars.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_stars: yes
          plugin_stars_limit: 2
          plugins_errors_fatal: yes
          config_timezone: Asia/Shanghai

      # Display recent activity metrics
      - name: Activity plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.activity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_activity: yes
          plugin_activity_limit: 4
          plugin_activity_days: 0
          plugin_activity_filter: push, issue, pr, release
          plugins_errors_fatal: yes
          config_timezone: Asia/Shanghai
          config_padding: 10%

      # This is used to illustrate special features with the use of "debug_flags"
      # - "--cakeday" will act as if it's your account birthday
      # - "--hireable" will act as if "Available for hire" is enabled on your account
      # - "--halloween" will act as if it was halloween, changing the colors of contributions calendar and isocalendar
      - name: Header (additional features)
        uses: lowlighter/metrics@master
        with:
          filename: metrics.header.svg
          token: ${{ secrets.METRICS_BOT_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "header"
          debug_flags: --cakeday --hireable --halloween
          plugins_errors_fatal: yes
          config_timezone: Asia/Shanghai

      # This is used to illustrate plugin errors :
      # The "METRICS_TOKEN" does not contains the "public_repo" scope, which is required for "plugin_projects"
      # It will display an "Insufficient token rights" error
      - name: Plugin error example
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.error.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_projects: yes
          plugins_errors_fatal: no
          config_timezone: Asia/Shanghai

      # Display followers and followed users
      # Note that :
      # - To respect privacy of users (as their faces could be displayed on every fork of this repository and on lowlighter/metrics),
      #   identicons option is used to hide their avatar, but you probably want to remove it if you use this plugin
      - name: People plugin (followers)
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.people.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_people: yes
          plugin_people_identicons: yes
          plugins_errors_fatal: yes
          config_timezone: Asia/Shanghai
